version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bus-shuttle-checker
    ports:
      - "8080:8080"
    environment:
      # App configuration
      - PORT=8080
      - CHECK_INTERVAL=60
      # Mailgun configuration - override these in your .env file
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN:-test.domain}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-test-key}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL:-test@example.com}
      - SENDER_EMAIL=${SENDER_EMAIL:-sender@example.com}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 