name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -o bus-shuttle-checker

    - name: Run application
      env:
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      run: ./bus-shuttle-checker 