name: Shuttle Availability Checker

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-availability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          check-latest: true

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run Shuttle Checker
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: |
          go run main.go check-all

      - name: Update Results Page
        run: |
          timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
          mkdir -p public
          cat > public/index.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
              <title>Shuttle Availability Status</title>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f5f5f5;
                  }
                  .container {
                      background-color: white;
                      padding: 20px;
                      border-radius: 8px;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  }
                  .header {
                      text-align: center;
                      margin-bottom: 20px;
                  }
                  .status {
                      margin-top: 20px;
                      padding: 15px;
                      border-radius: 4px;
                  }
                  .timestamp {
                      text-align: center;
                      color: #666;
                      margin-top: 20px;
                      font-size: 0.9em;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>Shuttle Availability Status</h1>
                  </div>
                  <div class="status">
                      <p>Last check: $timestamp</p>
                      <p>Status: Check completed</p>
                      <p>Note: If shuttles are available, you will receive an email notification.</p>
                  </div>
                  <div class="timestamp">
                      <p>This page auto-updates every 30 minutes</p>
                  </div>
              </div>
          </body>
          </html>
          EOL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true 