name: Shuttle Availability Checker

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-availability:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV

      - name: Run Shuttle Checker
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: |
          go run main.go check-all

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Update Results Page
        run: |
          timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
          mkdir -p public
          cat > public/index.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
              <title>Shuttle Availability Status</title>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <meta http-equiv="refresh" content="1800">
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      line-height: 1.6;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f5f5f5;
                  }
                  .container {
                      background-color: white;
                      padding: 20px;
                      border-radius: 8px;
                      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                  }
                  .header {
                      text-align: center;
                      margin-bottom: 20px;
                  }
                  .status {
                      margin-top: 20px;
                      padding: 15px;
                      border-radius: 4px;
                  }
                  .timestamp {
                      text-align: center;
                      color: #666;
                      margin-top: 20px;
                      font-size: 0.9em;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>Shuttle Availability Status</h1>
                  </div>
                  <div class="status">
                      <p>Last check: $timestamp</p>
                      <p>Status: Check completed</p>
                      <p>Note: If shuttles are available, you will receive an email notification.</p>
                  </div>
                  <div class="timestamp">
                      <p>This page auto-updates every 30 minutes</p>
                      <p><small>Next refresh in <span id="countdown">30:00</span></small></p>
                  </div>
              </div>
              <script>
                  function updateCountdown() {
                      const countdownEl = document.getElementById('countdown');
                      let [minutes, seconds] = countdownEl.textContent.split(':').map(Number);
                      
                      if (seconds > 0) {
                          seconds--;
                      } else if (minutes > 0) {
                          minutes--;
                          seconds = 59;
                      }
                      
                      countdownEl.textContent = \`\${minutes.toString().padStart(2, '0')}:\${seconds.toString().padStart(2, '0')}\`;
                  }
                  
                  setInterval(updateCountdown, 1000);
              </script>
          </body>
          </html>
          EOL

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 